apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: cluster1
spec:
  version: 7.15.1
  http:
    service:
      metadata:
        labels:
          app: cluster1
        annotations:
          cloud.google.com/app-protocols: '{"https":"HTTPS"}'
          service.alpha.kubernetes.io/app-protocols: '{"https":"HTTPS"}'
          cloud.google.com/neg: '{"ingress": true}'
  nodeSets:
  - name: elasticsearch
    count: 1
    config:
      xpack.security.authc:
        anonymous:
          username: anon
          roles: monitoring_user
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
          - name: elasticsearch
            readinessProbe:
              httpGet:
                scheme: HTTPS
                port: 9200
    volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 6Gi
            storageClassName: standard
